version: '3'
services:
  database:
    image: mysql:5.7.23
    command: --character-set-server=utf8 --collation-server=utf8_general_ci
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: memki      
    ports:
      - 3306:3306